/** Explicit provider opt-in over a bounded, authorized keyword shortlist. */
export const corpusDiscoveryMarkup=`<section id="corpus-discovery-section" hidden><h2>Compare API candidates for a task</h2><p>Your task and selected API documentation or source identifiers may be sent to the configured inference provider. This compares a bounded keyword shortlist across services. Suggestions are inferred, unreviewed and non-normative.</p><form id="corpus-discovery"><label>Environment <input name="environment" maxlength="512" required placeholder="e.g. uat"></label><label>Task or intent<textarea name="intentQuery" maxlength="512" required></textarea></label><button type="submit">Compare candidates with inference</button></form><p id="corpus-discovery-status" role="status"></p><ul id="corpus-discovery-results"></ul></section>`;
export const corpusDiscoveryScript=`
const corpusDiscoveryEnabled=__CORPUS_DISCOVERY_ENABLED__;
const corpusDiscoverySection=document.getElementById('corpus-discovery-section'),corpusDiscoveryForm=document.getElementById('corpus-discovery'),corpusDiscoveryStatus=document.getElementById('corpus-discovery-status'),corpusDiscoveryResults=document.getElementById('corpus-discovery-results');
corpusDiscoverySection.hidden=!corpusDiscoveryEnabled;
let corpusDiscoveryGeneration=0;
corpusDiscoveryForm.addEventListener('input',()=>{corpusDiscoveryGeneration++;corpusGeneration++;corpusDiscoveryResults.replaceChildren();corpusDiscoveryStatus.textContent='Inputs changed. Compare again to update suggestions.';});
const corpusDiscoverySamePin=(left,right)=>left&&right&&['snapshotId','revision','configFingerprint','checkpointVersion'].every(field=>left[field]===right[field])&&!Object.hasOwn(left,'selectedRevision')&&!Object.hasOwn(left,'pointerVersion');
const corpusDiscoverySameSelector=(left,right)=>left&&right&&left.kind==='environment'&&right.kind==='environment'&&left.environment===right.environment&&left.expectedCheckpointVersion===right.expectedCheckpointVersion;
const corpusDiscoveryGroups=(body,environment)=>{
  if(body.status!=='groups'||body.environment!==environment||body.scope!=='keyword_candidates'||body.verification!=='inferred'||body.review!=='unreviewed'||body.normative!==false||!Array.isArray(body.groups)||body.groups.length<1||body.groups.length>4||typeof body.shortlistCoverage?.complete!=='boolean'||typeof body.shortlistCoverage?.truncated!=='boolean')throw Error('invalid');
  let count=0;const names=new Set();
  for(const group of body.groups){const selected=group.selector,pin=group.pin,key=JSON.stringify([group.repositoryId,group.serviceId]);
    if(typeof group.repositoryId!=='string'||typeof group.serviceId!=='string'||names.has(key)||selected?.repositoryId!==group.repositoryId||selected?.serviceId!==group.serviceId||selected?.selector?.kind!=='environment'||selected.selector.environment!==environment||typeof pin?.checkpointVersion!=='string'||selected.selector.expectedCheckpointVersion!==pin.checkpointVersion||Object.hasOwn(pin,'selectedRevision')||Object.hasOwn(pin,'pointerVersion')||!['snapshotId','revision','configFingerprint'].every(field=>typeof pin[field]==='string')||!Array.isArray(group.candidates)||!group.candidates.length)throw Error('invalid');
    names.add(key);count+=group.candidates.length;if(count>16)throw Error('invalid');
    const ids=new Set();for(const item of group.candidates){if(item.repositoryId!==group.repositoryId||item.serviceId!==group.serviceId||item.selector?.tenantId!==selected.tenantId||item.selector?.repositoryId!==group.repositoryId||item.selector?.serviceId!==group.serviceId||typeof item.endpointId!=='string'||ids.has(item.endpointId)||typeof item.method!=='string'||typeof item.path!=='string'||!corpusDiscoverySamePin(item.pin,pin)||!corpusDiscoverySameSelector(item.selector?.selector,selected.selector))throw Error('invalid');ids.add(item.endpointId);}
    const result=group.result;if(!result||!['disabled','no_context','suggestions','ambiguous','no_match'].includes(result.status))throw Error('invalid');
    if(['suggestions','ambiguous','no_match'].includes(result.status)&&(result.verification!=='inferred'||result.review!=='unreviewed'||result.normative!==false||!corpusDiscoverySamePin(result.provenance?.pin,pin)||!corpusDiscoverySameSelector(result.provenance?.selector,selected.selector)))throw Error('invalid');
    if(result.status==='suggestions'&&(!Array.isArray(result.suggestions)||!result.suggestions.length||result.suggestions.some(item=>!ids.has(item.endpointId)||typeof item.intent!=='string'||typeof item.summary!=='string'||!Array.isArray(item.evidenceIds))))throw Error('invalid');
    if(result.status==='ambiguous'&&(!Array.isArray(result.candidateEndpointIds)||result.candidateEndpointIds.some(id=>!ids.has(id))))throw Error('invalid');
  }return body.groups;
};
corpusDiscoveryForm.addEventListener('submit',async event=>{
  event.preventDefault();const generation=++corpusDiscoveryGeneration;corpusDiscoveryResults.replaceChildren();const data=new FormData(corpusDiscoveryForm),environment=String(data.get('environment')||''),intentQuery=String(data.get('intentQuery')||'');
  corpusDiscoveryStatus.textContent='Comparing authorized API candidates…';
  try{const body=await fetchJson('/api/corpus-discover',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({environment,intentQuery,limit:16})});if(generation!==corpusDiscoveryGeneration)return;if(body.environment!==environment)throw Error('stale');
    if(body.status==='shortlist_no_match'){if(body.scope!=='keyword_candidates'||body.matchMode!=='keyword'||body.complete!==true||body.normative!==false)throw Error('invalid');corpusDiscoveryStatus.textContent='No keyword candidates were found. A suitable API may still exist outside this shortlist.';return;}
    if(body.status==='unknown'){corpusDiscoveryStatus.textContent='A bounded comparison is unavailable for this environment or shortlist.';return;}
    const groups=corpusDiscoveryGroups(body,environment),fragment=document.createDocumentFragment();
    for(const group of groups){const result=group.result,row=document.createElement('li'),title=document.createElement('p');title.textContent=group.repositoryId+' / '+group.serviceId+' (checkpoint '+group.pin.checkpointVersion+') — '+result.status;row.append(title);
      if(result.contextCoverage?.status==='partial'){const coverage=document.createElement('p');coverage.textContent='Context coverage is partial: '+result.contextCoverage.analyzedEndpointIds.length+' of '+result.contextCoverage.requestedEndpointIds.length+' operations analyzed.';row.append(coverage);}
      const suggestions=result.status==='suggestions'?result.suggestions:result.status==='ambiguous'?result.candidateEndpointIds.map(endpointId=>({endpointId,intent:'Ambiguous candidate',summary:result.reason,evidenceIds:[]})):[];
      for(const suggestion of suggestions){const item=group.candidates.find(candidate=>candidate.endpointId===suggestion.endpointId),description=document.createElement('p'),button=document.createElement('button');description.textContent=item.method+' '+item.path+' — '+suggestion.intent+': '+suggestion.summary+' (evidence: '+suggestion.evidenceIds.join(', ')+')';button.type='button';button.textContent='Load suggested pinned contract';button.addEventListener('click',()=>{if(generation!==corpusDiscoveryGeneration)return;pendingCorpusCandidate={item,generation:++corpusGeneration};contract.elements.namedItem('repositoryId').value=group.repositoryId;contract.elements.namedItem('serviceId').value=group.serviceId;contract.elements.namedItem('kind').value='environment';contract.elements.namedItem('value').value=environment;contract.dataset.expectedVersion=group.pin.checkpointVersion;contract.requestSubmit();});row.append(description,button);}
      fragment.append(row);
    }
    corpusDiscoveryResults.append(fragment);corpusDiscoveryStatus.textContent='Suggestions are inferred, unreviewed and non-normative. Compared only the keyword shortlist.'+(body.shortlistCoverage.complete?'':' Shortlist coverage is incomplete.')+(body.shortlistCoverage.truncated?' More candidates were omitted.':'');
  }catch{if(generation===corpusDiscoveryGeneration){corpusDiscoveryResults.replaceChildren();corpusDiscoveryStatus.textContent='Comparison is unavailable or its context changed. Try again.';}}
});
`;
