import {corpusDiscoveryMarkup} from "./corpus-discovery-browser.js";

export const page = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>API Truth</title><link rel="stylesheet" href="/style.css"></head>
<body><div class="shell"><aside class="sidebar"><a class="brand" href="#catalog"><span class="brand-mark">AT</span><span>API Truth<small>API intelligence</small></span></a><p class="nav-label">WORKSPACE</p><nav aria-label="Main navigation"><a href="#catalog" class="nav-current">Service catalogue</a><a href="#workspace">API workspace</a><a href="#comparison">Compare versions</a></nav><div class="sidebar-note"><span class="live-dot"></span> Evidence-backed contracts<p>Explore what your services expose.</p></div></aside><div class="main-area"><header class="topbar"><span>Workspace <span class="breadcrumb">/ API catalogue</span></span><span class="topbar-tag">Developer portal</span></header><main><div class="page-heading"><p class="eyebrow">DISCOVER · UNDERSTAND · BUILD</p><h1>Explore your APIs<span class="heading-dot">.</span></h1><p>Find a service, inspect its contract, and see the evidence behind each operation.</p></div>
<section id="catalog" class="card catalogue-card"><div class="section-heading"><div><p class="eyebrow">CATALOGUE</p><h2>Find a service</h2></div><span class="pill">Environment-aware</span></div><p class="muted">Search by service or repository name. Choose an environment to narrow your results.</p><form id="search"><label>Service or repository <input placeholder="Search services…" name="query" maxlength="128" autocomplete="off"></label>
<label>Environment <select name="environment" data-environment-select disabled><option value="">All environments</option></select></label>
<button type="submit">Search</button></form><p id="environment-status" role="status"></p><p id="search-status" role="status"></p><ul id="results"></ul></section>
${corpusDiscoveryMarkup}<section id="corpus-section" hidden><h2>Find API candidates across services</h2><p>Search existing authorized APIs by keyword in one current environment. Results are lexical candidates, not a guarantee that an API fulfills your task.</p><form id="corpus"><label>Environment <select name="environment" data-environment-select required disabled><option value="">Choose an environment</option></select></label><label>Task or intent<textarea name="intentQuery" maxlength="512" required></textarea></label><button type="submit">Search across services</button></form><p id="corpus-status" role="status"></p><ul id="corpus-results"></ul></section>
<section id="workspace" class="card contract-card"><div class="section-heading"><div><p class="eyebrow">API WORKSPACE</p><h2>View a contract</h2></div><span id="selected-service" class="pill">No service selected</span></div><p class="muted">Select a service above, or open a specific contract below.</p><form id="contract"><label>Repository <input name="repositoryId" maxlength="512" required></label>
<label>Service <input name="serviceId" maxlength="512" required></label><label>Selection
<select name="kind"><option value="environment">Environment</option><option value="branch">Branch</option>
<option value="revision">Revision</option></select></label>
<label>Name or revision <input name="value" maxlength="512" required placeholder="e.g. uat"></label>
<button type="submit">View contract</button></form><p id="contract-status" role="status"></p>
<div id="contract-summary" class="contract-metadata"></div><div class="contract-columns"><div class="operation-browser"><h3>Operations</h3><ul id="endpoints"></ul><details class="secondary-list"><summary>Schema components</summary><ul id="schemas"></ul></details><details class="secondary-list"><summary>Source evidence</summary><ul id="evidence"></ul></details></div><div class="detail-panel"><div id="detail-view"><div class="empty-detail"><span class="empty-icon">↗</span><h3>Your API, in detail</h3><p>Select an operation to see parameters, responses and source evidence.</p></div></div><details id="raw-detail"><summary>Inspect source JSON</summary><pre id="detail"></pre></details></div></div>
<a id="download" hidden>Download this published OpenAPI version</a></section>
<section id="presence" hidden><h2>Observed field presence</h2><p>Read which selected fields appeared in observed requests or responses. Values are hidden. These observations do not define required or optional fields.</p><form id="presence-form"><label>Policy ID <input name="policyId" maxlength="128" required autocomplete="off"></label><label>Policy version <input name="ownerPolicyRevision" maxlength="19" value="1" required inputmode="numeric"></label><label>Record limit <input name="limit" type="number" min="1" max="100" value="20" required></label><button type="submit" disabled>Read observed fields</button></form><p id="presence-status" role="status"></p><pre id="presence-result"></pre></section>
<section id="examples" hidden><h2>Synthetic schema example</h2><p>Generate a deterministic placeholder from a configured policy. It is synthetic, non-normative, and does not show observed traffic or prove runtime validation.</p><form id="example-form"><label>Policy ID <input name="policyId" maxlength="128" required autocomplete="off"></label><button type="submit" disabled>Generate synthetic example</button></form><p id="example-status" role="status"></p><pre id="example-result"></pre></section>
<section id="discovery" hidden><h2>Find an API for this task</h2><form id="candidates" hidden><p>Find keyword candidates in the current authorized environment. This checks words in existing API context; it does not use an inference provider.</p><label>Task or intent<textarea name="intentQuery" maxlength="512" required></textarea></label><button type="submit">Find candidate APIs</button></form><p id="candidate-status" role="status"></p><ul id="candidate-results"></ul><form id="discover"><p>Selected endpoint documentation, source route and handler identifiers, and your task text may be sent to the host-configured inference provider.</p><fieldset id="discovery-endpoints"><legend>Choose API operations</legend></fieldset><label>Task or intent<textarea name="intentQuery" maxlength="512" required></textarea></label><button type="submit">Find an API for this task</button></form><p id="discovery-status" role="status"></p><ul id="discovery-results"></ul></section>
<section id="comparison" class="card"><p class="eyebrow">CHANGE INTELLIGENCE</p><h2>Compare contracts</h2><p class="muted">See what changed between environments, branches or revisions.</p><form id="compare"><label>From
<select name="fromKind"><option value="environment">Environment</option><option value="branch">Branch</option>
<option value="revision">Revision</option></select></label><label>Name or revision <input name="fromValue" maxlength="512" required></label>
<label>To<select name="toKind"><option value="environment">Environment</option><option value="branch">Branch</option>
<option value="revision">Revision</option></select></label><label>Name or revision <input name="toValue" maxlength="512" required></label>
<button type="submit">Compare</button></form><p id="compare-status" role="status"></p><pre id="changes"></pre></section>
</main><footer>API Truth · Understand your APIs from evidence</footer></div></div><script src="/app.js" defer></script></body></html>`;
